services:
  pingpong-bot:
    build: .
    container_name: pingpong-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    environment:
      - DATA_DIR=/app/data
